### ISSUE TITLE
Structure JS and CSS in modular way

### ISSUE THREAD

**Issue by benedyktdryl** [katarzynam1405/geo-social#5]
## Goal

Achieve some basic structure with `bundles` and `modules`

## Description

- [ ] `bundles` directory with main bundle
- [ ]  `Button` module with `console.log` when clicking on it, bundled into main bundle
- [ ]  button styles excluded to `Button` module directory and imported in `Button` module

**Comment by benedyktdryl** [comment]
@katarzynam1405 this can be resolved now. It was not resolved correctly by PR because you forgot to put `#number_of_issue` after `Resolve` in ticket.

Please close this ticket and make reference to PR with `#number_of_pr`.

**Comment by katarzynam1405** [comment]
Closed by #6 pull request
